package org.jeson.reinforcetool.error;

public interface ErrorCode {

    int SUCCESS = 0;
    int FAILED_REINFORCE_ARGS_INVALID = 1;
    int FAILED_APK_DECODE = 3;
    int FAILED_APK_ENCODE = 4;
    int FAILED_DEX_PRETEND = 5;
    int FAILED_SIGNER_NULL_SOURCE_APK_ERROR = 7;
    int FAILED_SIGNER_NULL_DST_APK_ERROR = 8;
    int FAILED_SIGNER_PROCESSOR_ARGS_INVALID = 9;
    int FAILED_SIGNER_SIGN_APK_UNKNOWN_ERROR = 10;
    int FAILED_ZIPALIGN_EXECUTOR_INVALID = 11;
    int FAILED_ZIPALIGN_SOURCE_APK_INVALID = 12;
    int FAILED_ZIPALIGN_APK_UNKNOWN_ERROR = 13;
    int FAILED_ARGS_ERROR = 255;
}
